def personal_sum(numbers):
    result = 0
    error_result = 0

    for i in numbers:
        try:
            result += i
        except TypeError:
            print(f'Некорректный тип данных для подсчёта суммы - {i}')
            error_result += 1

    return result, error_result


def calculate_average(numbers):
    try:
        total_sum, error_count = personal_sum(numbers)
        count = len(numbers) - error_count

        if count == 0:
            return 0
        return total_sum / count
    except TypeError:
        print('В numbers записан некорректный тип данных')
        return None



print(f'Результат 1: {calculate_average("1, 2, 3")}') # Строка перебирается, но каждый символ - строковый тип
print(f'Результат 2: {calculate_average([1, "Строка", 3, "Ещё Строка"])}') # Учитываются только 1 и 3
print(f'Результат 3: {calculate_average(567)}') # Передана не коллекция
print(f'Результат 4: {calculate_average([42, 15, 36, 13])}') # Всё должно работать